<?php
declare(strict_types=1);

namespace MonkeysLegion\Core\Opcache;

/**
 * MonKeysLegion Framework — Core Package
 *
 * Generates an OPcache preload script (bin/preload.php) that preloads
 * all framework core classes, compiled container, and compiled routes
 * into OPcache for zero cold-start penalty.
 *
 * The generated script uses opcache_compile_file() for each class file,
 * wrapped in try/catch to skip classes that cannot be preloaded.
 *
 * @copyright 2026 MonKeysCloud Team
 * @license   MIT
 */
final class PreloadGenerator
{
    /** @var list<string> Framework namespace prefixes to preload */
    private readonly array $frameworkPrefixes;

    /** @var list<string> Additional paths to preload (compiled container, routes) */
    private readonly array $extraPaths;

    public function __construct(
        private readonly string $basePath,
        array $frameworkPrefixes = [
            'MonkeysLegion\\Core\\',
            'MonkeysLegion\\Http\\',
            'MonkeysLegion\\Router\\',
            'MonkeysLegion\\DI\\',
            'MonkeysLegion\\Template\\',
            'MonkeysLegion\\Query\\',
            'MonkeysLegion\\Entity\\',
            'MonkeysLegion\\Validation\\',
            'MonkeysLegion\\Auth\\',
            'MonkeysLegion\\Session\\',
            'MonkeysLegion\\Cache\\',
            'MonkeysLegion\\Queue\\',
            'MonkeysLegion\\Mail\\',
            'MonkeysLegion\\CLI\\',
            'MonkeysLegion\\MLC\\',
            'MonkeysLegion\\OpenApi\\',
            'MonkeysLegion\\Telemetry\\',
            'MonkeysLegion\\RateLimit\\',
            'MonkeysLegion\\Inertia\\',
            'MonkeysLegion\\Vite\\',
            'MonkeysLegion\\Resources\\',
            'Psr\\Http\\',
            'Psr\\Container\\',
            'Psr\\Log\\',
            'Psr\\Cache\\',
            'Psr\\SimpleCache\\',
        ],
        ?array $extraPaths = null,
    ) {
        $this->frameworkPrefixes = $frameworkPrefixes;
        $this->extraPaths = $extraPaths ?? [
            $basePath . '/storage/framework/container/CompiledContainer.php',
            $basePath . '/storage/framework/routes/routes.cache',
            $basePath . '/storage/framework/config/config.cache',
        ];
    }

    /**
     * Generate the preload script and write it to the output path.
     *
     * @param string $outputPath Target file path (default: bin/preload.php).
     * @return array{written: int, skipped: int, file: string} Stats.
     */
    public function generate(string $outputPath = ''): array
    {
        if ($outputPath === '') {
            $outputPath = $this->basePath . '/bin/preload.php';
        }

        $classes = $this->collectClasses();
        $extraFiles = $this->collectExtraFiles();

        $allFiles = array_merge($classes, $extraFiles);
        $allFiles = array_unique($allFiles);
        $allFiles = array_filter($allFiles, fn($f) => is_file($f) && str_ends_with($f, '.php'));

        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = 'declare(strict_types=1);';
        $lines[] = '';
        $lines[] = '/**';
        $lines[] = ' * OPcache Preload Script — MonKeysLegion Framework';
        $lines[] = ' * Auto-generated by `ml preload:generate`';
        $lines[] = ' * Generated: ' . date('Y-m-d H:i:s');
        $lines[] = ' *';
        $lines[] = ' * Usage (php.ini):';
        $lines[] = ' *   opcache.preload=/path/to/bin/preload.php';
        $lines[] = ' *   opcache.preload_user=root';
        $lines[] = ' */';
        $lines[] = '';
        $lines[] = '// Ensure OPcache is available';
        $lines[] = 'if (!function_exists(\'opcache_compile_file\')) {';
        $lines[] = '    return; // OPcache not available — skip silently';
        $lines[] = '}';
        $lines[] = '';
        $lines[] = '$preloaded = 0;';
        $lines[] = '$skipped = 0;';
        $lines[] = '';
        $lines[] = '// ── Framework core classes ────────────────────────────────';
        $lines[] = '';

        foreach ($allFiles as $file) {
            $escapedPath = var_export($file, true);
            $lines[] = 'try {';
            $lines[] = '    opcache_compile_file(' . $escapedPath . ');';
            $lines[] = '    $preloaded++;';
            $lines[] = '} catch (\Throwable $e) {';
            $lines[] = '    $skipped++; // Skip: ' . basename($file);
            $lines[] = '}';
            $lines[] = '';
        }

        $lines[] = '// ── Summary ───────────────────────────────────────────────';
        $lines[] = '// Preloaded: $preloaded files, Skipped: $skipped files';
        $lines[] = '// Configure php.ini: opcache.preload=' . $outputPath;

        $content = implode("\n", $lines) . "\n";

        $dir = dirname($outputPath);
        if (!is_dir($dir)) {
            @mkdir($dir, 0755, true);
        }

        file_put_contents($outputPath, $content);

        return [
            'written' => count($allFiles),
            'skipped' => 0, // Actual skip count only known at preload time
            'file'    => $outputPath,
        ];
    }

    /**
     * Collect all framework class file paths from the Composer classmap.
     *
     * @return list<string>
     */
    private function collectClasses(): array
    {
        $classmapPath = $this->basePath . '/vendor/composer/autoload_classmap.php';

        if (!is_file($classmapPath)) {
            return [];
        }

        /** @var array<string, string> $classmap */
        $classmap = require $classmapPath;

        $files = [];
        foreach ($classmap as $class => $path) {
            foreach ($this->frameworkPrefixes as $prefix) {
                if (str_starts_with($class, $prefix)) {
                    $files[] = $path;
                    break;
                }
            }
        }

        return $files;
    }

    /**
     * Collect extra file paths (compiled container, routes, config).
     *
     * @return list<string>
     */
    private function collectExtraFiles(): array
    {
        return array_filter($this->extraPaths, fn($p) => is_file($p) && str_ends_with($p, '.php'));
    }

    /**
     * Get the list of framework namespace prefixes being preloaded.
     *
     * @return list<string>
     */
    public function getFrameworkPrefixes(): array
    {
        return $this->frameworkPrefixes;
    }
}
